# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfiPdrIy6tk7s_kN7naZ_i4qOQzlra-j
"""

def parse_raw_can_frame(raw_frame):
    if len(raw_frame) < 3:
        raise ValueError("Frame too short to contain ID and DLC")

    # Extract arbitration ID (2 bytes)
    arbitration_id = (raw_frame[0] << 8) | raw_frame[1]

    # Extract DLC (1 byte)
    dlc = raw_frame[2]
    if dlc > 8:
        raise ValueError("DLC cannot be more than 8")

    # Extract data bytes
    data = raw_frame[3:3+dlc]

    return {
        "arbitration_id": arbitration_id,
        "dlc": dlc,
        "data": data
    }

